# Generated by Django 2.2 on 2019-10-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=200)),
                ('stockcode', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('invoicedate', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('customerid', models.IntegerField()),
            ],
        ),
    ]
