# Generated by Django 2.2 on 2019-10-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20191025_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='price',
            field=models.FloatField(),
        ),
    ]
